spring.application.name=crud-app

logging.level.org.springframework=DEBUG

spring.datasource.url=jdbc:mysql://localhost:3306/empdb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

javers.newObjectSnapshot=true  # Ensures snapshots are created even for new entities

logging.level.org.javers=DEBUG